set(GLFW_PATH "INSERT PATH HERE")
set(GLM_PATH "INSERT PATH HERE")
set(VULKAN_SDK_PATH "INSERT PATH HERE")

# Set MINGW_PATH if using mingw not visual studio
#set(MINGW_PATH "INSERT PATH HERE")

# Optional external lib paths
#set(TINYOBJ_PATH "INSERT PATH HERE")
#set(TINYGLTF_PATH "INSERT PATH HERE")
#set(IMGUI_PATH "INSERT PATH HERE")
#set(MIKKTSPACE_PATH "INSERT PATH HERE")